version: '3'

services:
  api:
    build: .
    ports:
      - "5000:5000"
    restart: always
    environment:
      # API密钥配置（从环境变量或.env文件获取）
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - CLAUDE_API_KEY=${CLAUDE_API_KEY}
      - ALI_BAILIAN_API_KEY=${ALI_BAILIAN_API_KEY}
      - SILICONFLOW_API_KEY=${SILICONFLOW_API_KEY}
      - SERPER_API_KEY=${SERPER_API_KEY}
      - TAVILY_API_KEY=${TAVILY_API_KEY}
      - DEERAPI_API_KEY=${DEERAPI_API_KEY}
    volumes:
      # 映射本地目录用于文件上传和日志
      - ./uploads:/app/uploads
      - ./logs:/app/logs
    command: python app.py
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3" 